# Generated by Django 2.2.7 on 2020-03-11 19:03

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_header', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfroalasuperheader',
            name='classes',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительные классы блока'),
        ),
        migrations.AddField(
            model_name='superheaderconf',
            name='color_line',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', max_length=18, null=True),
        ),
    ]
