# Generated by Django 2.2.7 on 2020-03-12 08:45

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftIconTextConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Стандартный', max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(default='std', max_length=255, unique=True, verbose_name='Название класса')),
                ('classes', models.CharField(blank=True, default='my-2', max_length=255, null=True, verbose_name='Дополнительные классы блока')),
                ('col_ico_classes', models.CharField(default='col-4 d-flex align-items-center', max_length=255, verbose_name='Классы иконки')),
                ('col_html_classes', models.CharField(default='col-8', max_length=255, verbose_name='Классы иконки')),
                ('icon_size', models.IntegerField(default='50', verbose_name='Размер иконки')),
                ('color_icon', colorfield.fields.ColorField(blank=True, default='text-body', max_length=18, null=True)),
                ('align', models.CharField(choices=[('left', 'left'), ('right', 'right')], default='left', max_length=255, verbose_name='Положение иконки')),
            ],
        ),
        migrations.CreateModel(
            name='ModelFroalaLeftIconText',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='left_icon_text_modelfroalalefticontext', serialize=False, to='cms.CMSPlugin')),
                ('ico', models.CharField(default='fa fa-cutlery fa-fw', max_length=255, verbose_name='Классы иконки')),
                ('classes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительные классы блока')),
                ('conf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='left_icon_text.LeftIconTextConf')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
