# Generated by Django 2.2.7 on 2020-03-12 08:51

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('left_icon_text', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lefticontextconf',
            old_name='icon_size',
            new_name='ico_size',
        ),
        migrations.RemoveField(
            model_name='lefticontextconf',
            name='color_icon',
        ),
        migrations.AddField(
            model_name='lefticontextconf',
            name='color_ico',
            field=colorfield.fields.ColorField(blank=True, default='', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='lefticontextconf',
            name='col_html_classes',
            field=models.CharField(default='col-8 text-primary', max_length=255, verbose_name='Классы иконки'),
        ),
    ]
