# Generated by Django 2.2.7 on 2020-03-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('left_icon_text', '0002_auto_20200312_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lefticontextconf',
            name='classes',
            field=models.CharField(blank=True, default='row my-2', max_length=255, null=True, verbose_name='Дополнительные классы блока'),
        ),
        migrations.AlterField(
            model_name='lefticontextconf',
            name='col_html_classes',
            field=models.CharField(default='col-8', max_length=255, verbose_name='Классы иконки'),
        ),
        migrations.AlterField(
            model_name='lefticontextconf',
            name='col_ico_classes',
            field=models.CharField(default='col-4 d-flex align-items-center text-primary', max_length=255, verbose_name='Классы иконки'),
        ),
        migrations.AlterField(
            model_name='modelfroalalefticontext',
            name='classes',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Дополнительные классы блока'),
        ),
    ]
