# Generated by Django 2.2.7 on 2020-03-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('left_icon_text', '0003_auto_20200312_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lefticontextconf',
            name='classes',
            field=models.CharField(blank=True, default='my-2', max_length=255, null=True, verbose_name='Дополнительные классы блока'),
        ),
    ]
