# Generated by Django 2.2.7 on 2020-03-10 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelLeftBigImg3pluses',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='leftbigimg_3pluses_modelleftbigimg3pluses', serialize=False, to='cms.CMSPlugin')),
                ('html1', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Текст')),
                ('html2', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Текст')),
                ('html3', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Текст')),
                ('pic1', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение 1')),
                ('pic2', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение 2')),
                ('pic3', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение 3')),
                ('pic_big', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение слева большое')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
