# Generated by Django 2.2.7 on 2020-03-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftbigimg_3pluses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelleftbigimg3pluses',
            name='ico1',
            field=models.CharField(blank=True, help_text='Вместо изображения', max_length=255, null=True, verbose_name='Иконка 1'),
        ),
        migrations.AddField(
            model_name='modelleftbigimg3pluses',
            name='ico2',
            field=models.CharField(blank=True, help_text='Вместо изображения', max_length=255, null=True, verbose_name='Иконка 2'),
        ),
        migrations.AddField(
            model_name='modelleftbigimg3pluses',
            name='ico3',
            field=models.CharField(blank=True, help_text='Вместо изображения', max_length=255, null=True, verbose_name='Иконка 3'),
        ),
    ]
