# Generated by Django 2.2.7 on 2020-03-13 12:03

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_title', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTitleConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Стандартный', max_length=255, verbose_name='Название')),
                ('color', colorfield.fields.ColorField(blank=True, default='', max_length=18, null=True, verbose_name='Цвет наложения')),
                ('blend_mode', models.CharField(choices=[('normal', 'normal'), ('multiply', 'multiply'), ('screen', 'screen'), ('overlay', 'overlay'), ('darken', 'darken'), ('lighten', 'lighten'), ('color-dodge', 'color-dodge'), ('color-burn', 'color-burn'), ('hard-light', 'hard-light'), ('soft-light', 'soft-light'), ('difference', 'difference'), ('exclusion', 'exclusion'), ('hue', 'hue'), ('saturation', 'saturation'), ('color', 'color'), ('luminosity', 'luminosity')], default='darken', max_length=255, verbose_name='Эффект наложения')),
            ],
        ),
        migrations.AddField(
            model_name='modelpagetitle',
            name='conf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='page_title.PageTitleConf'),
        ),
    ]
