# Generated by Django 2.2.7 on 2020-03-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_text', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfroalaserviceimgtext',
            name='link_text',
            field=models.CharField(blank=True, default='Подробнее', max_length=255, null=True, verbose_name='Текст ссылки'),
        ),
    ]
